// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bar': string;
  'label': string;
  'metricLeft': string;
  'metricMiddle': string;
  'metricRight': string;
  'metricRow': string;
  'metricSpacer': string;
  'spacerRow': string;
  'tooltipBody': string;
  'value': string;
  'warningBar': string;
  'warningValue': string;
}
export const cssExports: CssExports;
export default cssExports;
